# coding: utf-8
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0’
use_frameworks!

target ‘EpitechEisenhower’ do
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
end
